/** @type {import('tailwindcss').Config} */
import daisyui from 'daisyui';
import { addDynamicIconSelectors } from "@iconify/tailwind";
export default {
  content: ["./src/**/*.{html,js,vue}"],
  darkMode: ['class', '[class="dark"]'],
  theme: {

  },
  prefix: '',
  plugins: [daisyui, addDynamicIconSelectors()],
  daisyui: {
    // 所有daisyui的主题，不用的可以注释掉
    themes: [
      'winter',
      {
        mytheme: {
          primary: '#5f70fa',
          secondary: '#26a69a',
          accent: '#9c27b0',
          neutral: '#2f2d39',
          info: '#23b1dd',
          success: '#6ec646',
          warning: '#feb43f',
          error: '#fe4d4d',
          'base-100': '#2f344d',
          'base-200': '#272b41',
          'base-300': '#222535',
        },
      },
      {
        vela: {
          primary: '#ffcc47',
          secondary: '#78909b',
          accent: '#9c27b0',
          neutral: '#2f2d39',
          info: '#cc94d5',
          success: '#6ec646',
          warning: '#feb43f',
          error: '#fe4d4d',
          'base-100': '#1e2d3f',
          'base-200': '#16212e',
          'base-300': '#222535',
        },
      },
      {
        blue: {
          primary: '#2045d8',
          secondary: '#01bdd3',
          accent: '#9c27b0',
          neutral: '#2f2d39',
          info: '#cc94d5',
          success: '#6ec646',
          warning: '#feb43f',
          error: '#fe4d4d',
          'base-100': '#0a1655',
          'base-200': '#0c175a',
          'base-300': '#010843',
        },
      },
      'mytheme',
      'vela',
      'blue',
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
    ],

    // 自定义配置，用于识别暗色主题
    darkThemes: [
      'mytheme',
      'vela',
      'blue',
      'dark',
      'synthwave',
      'halloween',
      'forest',
      'aqua',
      'black',
      'luxury',
      'dracula',
      'business',
      'night',
      'coffee',
    ],
    prefix: '',
  },
}
